### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by M1n01** [M1n01/ft_transcendence#1]
# 各環境構築
## Frontend
- [x] VanillaJS
- [x] bootstrap
### tools
- [x] [ESLint](https://qiita.com/mzmz__02/items/63f2624e00c02be2f942)(コーディングルール)
- [x] [Prettier](https://zenn.dev/ianchen0419/articles/bcb7f633928970)(コード自動整形)

## Backend
- [x] Django(確定)

### tools
- [x] [Black](https://qiita.com/muramasa2/items/29042acc11fed2ecb8c8)

## Database
- [x] PostgreSQL

## Blockchain
- [x] Solidity

## その他
- Docker compose
- Makefile

**Comment by M1n01** [comment]
~ESLintが使えなさそうなので、~ ESLintとvscodeの拡張機能[Prettier](https://zenn.dev/ianchen0419/articles/bcb7f633928970)を使いましょう。

6/16追記
node.jsをフレームワークと勘違いしており、npmを使用できないものだと勘違いしてました。
[こちら](https://discord.com/channels/1251130362382385172/1251786240098045972/1251787418718437387)の記事によると両方使用した方がいいようです。

**Comment by M1n01** [comment]
javascriptのフォーマッター、ESLintの設定ファイル(`.prettierrc.json`, `eslint.config.cjs`)を作成しました。

以下のコマンドを実行し、ESLintとPrettier、Blackの拡張機能を入れてください。
```
$ npm install
```
コマンドで`git commit -m "<commit message>"`とすると、ESLintが動作します。（しなかったら教えてください）。
VS Codeのコミット機能からの方法は分からなかったので、あれば教えてください！

もし分からないことや足りないことがあれば聞いてください！！

**Comment by hsano333** [comment]
![スクリーンショット 2024-06-25 022759](https://github.com/M1n01/ft_transcendence/assets/115250500/6bd4c3c0-8a86-47c8-8441-1a1d00a4ccc6)
対応ありがとうございます

>ESLintとPrettier、Blackの拡張機能を入れてください。

これはVS Codeの拡張機能として入れればいいですか？

>git commit -m "<commit message>"とすると、ESLintが動作します

ESLintが動作した結果どうなるのが正常ですか？


いろいろと触ってみたところ、動いているかどうかはちょっと怪しいです・・・
その理由はちょっと長くなりますが書き出します

1. 　eslint.config.cjsファイル内で示しているincludeは指定してディレクトリ内のファイルをeslintでテストするという意味だと思いますが、これを変更しても反応しない（現状srcディレクトリは存在しないため、該当ディレクトリ名に変更したが反応がなかった）
2.  上記結果を受けて、あらためてsrcディレクトリを作成し、その中に成果物全てをいれてgit commitするとeslint.config.cjs上のエラーが表示される（下記参照）。

`sano@webserv:~/work/42/ft_transcendence/ft_transcendence$ git commit -m "te"
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 1 file
    ❯ src/**/*.{js,jsx} — 1 file
      ✔ prettier --write --loglevel=error
      ✖ eslint --fix --quiet [FAILED]
    ↓ {public,src}/**/*.{html,gql,graphql,json} — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --fix --quiet:

Oops! Something went wrong! :(

ESLint: 9.5.0

A config object is using the "extends" key, which is not supported in flat config system.

Instead of "extends", you can include config objects that you'd like to extend from directly in the flat config array.

If you're using "extends" in your config file, please see the following:
https://eslint.org/docs/latest/use/configure/migration-guide#predefined-and-shareable-configs

If you're not using "extends" directly (it may be coming from a plugin), please see the following:
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config`

3.  eslint.config.cjsファイルを簡略化して以下のようにすると、eslintが正常に実行されて、いろいろとコード上のエラーが表示される（添付ファイル参照）。
`module.exports = {
  rules: {
    indent: ['error', 2],
    quotes: ['error', 'single'],
  },
};`


おそらく、eslint.config.cjsの何かが原因でエラーになり、実行されていません

**Comment by M1n01** [comment]
package.jsonの変更も必要でした。
上記対応したのでご確認ください。
